[build]
  command = "npm run build && npm run export"
  publish = "out"
  functions = "lambda"
[dev]
  framework = "next"
  command = "npm run dev"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200